### PR TITLE
Update win10.global.reg

### PR DESCRIPTION
**Pull request by sharky009**
removed code thats not longer needed with Samba 4.x

### CODE REVIEW

**Comment by HappyBasher** [comment]
@PLanB2008 Can you confirm that these patches can be removed?

**Comment by HappyBasher** [comment]
@PLanB2008 Can you confirm that these patches can be removed?

**Comment by PLanB2008** [comment]
I don't think this is a good idea. 
Indeed its not necessary to join the domain, but allowing the workstation to change the machinepassword imho breaks the linbo mechanism used for cloning, especially now when linbo syncs the machine password on every start (green, red yellow)

**Comment by HappyBasher** [comment]
So we leave it as it is.

**Pull request closed without merging**
